name: trackmyroute_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^11.2.0
  dio: ^5.7.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
  fluttertoast: ^8.2.2
  http: ^1.1.0
  get_it: ^7.6.4
  injectable: ^2.3.2
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  path: ^1.8.3
  http_parser: ^4.0.2
  flutter_image_slideshow: ^0.1.6
  flutter_credit_card: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
