# Establece la versión mínima de iOS en 14.0
platform :ios, '14.0'

# Usa frameworks estáticos
use_frameworks! :linkage => :static

# Desactiva las estadísticas de CocoaPods para reducir la latencia de construcción
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Configuración del proyecto para Flutter
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Ruta para la configuración de Flutter
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

# Requiere el podhelper de Flutter
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

# Configuración de pods de iOS para Flutter
flutter_ios_podfile_setup

# Configuración del target principal
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Instala todos los pods necesarios para Flutter
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Agrega el pod PhoneNumberKit explícitamente
  pod 'PhoneNumberKit', '~> 3.3'
  
  # Configuración para pruebas
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# Configuraciones adicionales después de la instalación de pods
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Asegúrate de que todos los targets usen al menos iOS 14.0
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end